import type {
  MockUser,
  Driver,
  Business,
  Delivery,
  SystemSettings,
  ManifestItem,
  StatusEvent,
} from './types'

// Helper to generate timestamps
const hoursAgo = (hours: number): string => {
  const date = new Date()
  date.setHours(date.getHours() - hours)
  return date.toISOString()
}

const minsAgo = (mins: number): string => {
  const date = new Date()
  date.setMinutes(date.getMinutes() - mins)
  return date.toISOString()
}

// Mock Users
export const mockUsers: MockUser[] = [
  {
    email: 'admin@lvcourier.ca',
    password: 'admin123',
    role: 'admin',
    name: 'Admin',
  },
  {
    email: 'marcus@lvcourier.ca',
    password: 'driver123',
    role: 'driver',
    driverId: 'driver-1',
    name: 'Marcus Reid',
  },
  {
    email: 'freshmart@lvcourier.ca',
    password: 'business123',
    role: 'business',
    businessId: 'business-1',
    locationId: 'location-1',
    name: 'FreshMart Grocery',
  },
]

// Mock Drivers
export const initialDrivers: Driver[] = [
  {
    id: 'driver-1',
    name: 'Marcus Reid',
    phone: '(403) 555-0101',
    email: 'marcus@lvcourier.ca',
    status: 'available',
    maxJobsOverride: null,
    totalDeliveries: 127,
    todayDeliveries: 3,
    monthDeliveries: 23,
    averageTime: '22 min',
    rushSlaRate: 94,
    monthlyAdjustments: 2,
    inviteStatus: 'active',
  },
  {
    id: 'driver-2',
    name: 'Jenna Cole',
    phone: '(403) 555-0102',
    email: 'jenna@lvcourier.ca',
    status: 'on_delivery',
    maxJobsOverride: null,
    totalDeliveries: 203,
    todayDeliveries: 5,
    monthDeliveries: 41,
    averageTime: '18 min',
    rushSlaRate: 97,
    monthlyAdjustments: 1,
    inviteStatus: 'active',
  },
  {
    id: 'driver-3',
    name: 'Tariq Hassan',
    phone: '(403) 555-0103',
    email: 'tariq@lvcourier.ca',
    status: 'available',
    maxJobsOverride: 2,
    totalDeliveries: 89,
    todayDeliveries: 2,
    monthDeliveries: 28,
    averageTime: '31 min',
    rushSlaRate: 88,
    monthlyAdjustments: 4,
    inviteStatus: 'active',
  },
  {
    id: 'driver-4',
    name: 'Sasha Kim',
    phone: '(403) 555-0104',
    email: 'sasha@lvcourier.ca',
    status: 'off_duty',
    maxJobsOverride: null,
    totalDeliveries: 156,
    todayDeliveries: 0,
    monthDeliveries: 19,
    averageTime: '24 min',
    rushSlaRate: 91,
    monthlyAdjustments: 0,
    inviteStatus: 'active',
  },
]

// Mock Businesses
export const initialBusinesses: Business[] = [
  {
    id: 'business-1',
    name: 'FreshMart Grocery',
    invoiceFormat: 'combined',
    inviteStatus: 'active',
    locations: [
      {
        id: 'location-1',
        businessId: 'business-1',
        name: 'Shawnessy',
        address: '250 Shawville Blvd SE, Calgary, AB T2Y 3Z1',
        billingEmail: 'billing@freshmart.ca',
        backupEmail: 'manager@freshmart.ca',
        contactName: 'Sarah Chen',
        phone: '(403) 555-0201',
        savedAddresses: [
          {
            id: 'addr-1',
            label: 'Main Location',
            address: '250 Shawville Blvd SE, Calgary, AB',
            area: 'Shawnessy',
            postalCode: 'T2Y 3Z1',
          },
          {
            id: 'addr-2',
            label: 'Warehouse',
            address: '8180 11 St SE, Calgary, AB',
            area: 'Shepard',
            postalCode: 'T2H 2S9',
          },
        ],
      },
      {
        id: 'location-2',
        businessId: 'business-1',
        name: 'Brentwood',
        address: '4820 Northland Dr NW, Calgary, AB T2L 2L4',
        billingEmail: 'billing@freshmart.ca',
        backupEmail: 'brentwood@freshmart.ca',
        contactName: 'Mike Johnson',
        phone: '(403) 555-0202',
        savedAddresses: [
          {
            id: 'addr-3',
            label: 'Store Location',
            address: '4820 Northland Dr NW, Calgary, AB',
            area: 'Dalhousie',
            postalCode: 'T2L 2L4',
          },
        ],
      },
    ],
  },
  {
    id: 'business-2',
    name: 'MedSupply Co',
    invoiceFormat: 'separate',
    inviteStatus: 'active',
    locations: [
      {
        id: 'location-3',
        businessId: 'business-2',
        name: 'Main Office',
        address: '1111 Centre St N, Calgary, AB T2E 2R2',
        billingEmail: 'accounts@medsupply.ca',
        backupEmail: 'admin@medsupply.ca',
        contactName: 'Dr. Patel',
        phone: '(403) 555-0301',
        savedAddresses: [],
      },
    ],
  },
  {
    id: 'business-3',
    name: 'HomeGoods Plus',
    invoiceFormat: 'combined_breakdown',
    inviteStatus: 'pending',
    locations: [
      {
        id: 'location-4',
        businessId: 'business-3',
        name: 'Downtown',
        address: '3009 14 St SW, Calgary, AB T2T 3V6',
        billingEmail: 'finance@homegoods.ca',
        backupEmail: '',
        contactName: 'Tom Wilson',
        phone: '(403) 555-0401',
        savedAddresses: [],
      },
    ],
  },
]

// Helper to create manifest items
const createManifestItem = (
  type: ManifestItem['type'],
  qty: number = 1,
  notes: string = ''
): ManifestItem => ({
  id: `item-${Math.random().toString(36).slice(2, 9)}`,
  type,
  postedQty: qty,
  confirmedQty: null,
  verificationPhotoUrl: null,
  notes,
})

// Helper to create status event
const createStatusEvent = (
  status: StatusEvent['status'],
  timestamp: string,
  note: string | null = null
): StatusEvent => ({
  status,
  timestamp,
  note,
  gpsLat: null,
  gpsLng: null,
})

// Mock Deliveries
export const initialDeliveries: Delivery[] = [
  // Posted - awaiting driver (urgent)
  {
    id: 'del-001',
    businessId: 'business-1',
    locationId: 'location-1',
    businessName: 'FreshMart Grocery',
    driverId: null,
    driverName: null,
    pickupAddress: '250 Shawville Blvd SE, Calgary, AB T2Y 3Z1',
    pickupArea: 'Shawnessy',
    dropoffAddress: '130 Crowfoot Crescent NW, Calgary, AB T3G 3P5',
    dropoffArea: 'Crowfoot',
    recipientPhone: '(403) 555-1001',
    manifest: [
      createManifestItem('big_package', 3, 'Handle with care - groceries'),
      createManifestItem('rush'),
    ],
    isUrgent: true,
    isOutOfTown: false,
    status: 'posted',
    postedAt: minsAgo(12),
    claimedAt: null,
    pickedUpAt: null,
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [],
    statusHistory: [createStatusEvent('posted', minsAgo(12))],
    trackingCode: null,
    tripId: null,
    retryCount: 0,
  },
  // Posted - awaiting driver (regular)
  {
    id: 'del-002',
    businessId: 'business-2',
    locationId: 'location-3',
    businessName: 'MedSupply Co',
    driverId: null,
    driverName: null,
    pickupAddress: '1111 Centre St N, Calgary, AB T2E 2R2',
    pickupArea: 'Crescent Heights',
    dropoffAddress: '7015 Macleod Trail SW, Calgary, AB T2H 2K6',
    dropoffArea: 'Chinook',
    recipientPhone: '(403) 555-1002',
    manifest: [createManifestItem('small_package', 1, 'Medical supplies - fragile')],
    isUrgent: false,
    isOutOfTown: false,
    status: 'posted',
    postedAt: minsAgo(25),
    claimedAt: null,
    pickedUpAt: null,
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [],
    statusHistory: [createStatusEvent('posted', minsAgo(25))],
    trackingCode: null,
    tripId: null,
    retryCount: 0,
  },
  // Claimed by Marcus
  {
    id: 'del-003',
    businessId: 'business-1',
    locationId: 'location-2',
    businessName: 'FreshMart Grocery',
    driverId: 'driver-1',
    driverName: 'Marcus Reid',
    pickupAddress: '4820 Northland Dr NW, Calgary, AB T2L 2L4',
    pickupArea: 'Dalhousie',
    dropoffAddress: '901 64 Ave NE, Calgary, AB T2E 7P4',
    dropoffArea: 'Marlborough',
    recipientPhone: '(403) 555-1003',
    manifest: [createManifestItem('big_package', 2)],
    isUrgent: false,
    isOutOfTown: false,
    status: 'claimed',
    postedAt: minsAgo(45),
    claimedAt: minsAgo(8),
    pickedUpAt: null,
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [],
    statusHistory: [
      createStatusEvent('posted', minsAgo(45)),
      createStatusEvent('claimed', minsAgo(8), 'Claimed by Marcus Reid'),
    ],
    trackingCode: null,
    tripId: null,
    retryCount: 0,
  },
  // En route to pickup - Jenna
  {
    id: 'del-004',
    businessId: 'business-2',
    locationId: 'location-3',
    businessName: 'MedSupply Co',
    driverId: 'driver-2',
    driverName: 'Jenna Cole',
    pickupAddress: '1111 Centre St N, Calgary, AB T2E 2R2',
    pickupArea: 'Crescent Heights',
    dropoffAddress: '5149 Country Hills Blvd NW, Calgary, AB T3A 5K8',
    dropoffArea: 'Country Hills',
    recipientPhone: '(403) 555-1004',
    manifest: [
      createManifestItem('small_package', 1),
      createManifestItem('rush'),
    ],
    isUrgent: true,
    isOutOfTown: false,
    status: 'en_route_pickup',
    postedAt: minsAgo(35),
    claimedAt: minsAgo(15),
    pickedUpAt: null,
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [],
    statusHistory: [
      createStatusEvent('posted', minsAgo(35)),
      createStatusEvent('claimed', minsAgo(15), 'Claimed by Jenna Cole'),
      createStatusEvent('en_route_pickup', minsAgo(12)),
    ],
    trackingCode: null,
    tripId: null,
    retryCount: 0,
  },
  // Picked up - Tariq
  {
    id: 'del-005',
    businessId: 'business-1',
    locationId: 'location-1',
    businessName: 'FreshMart Grocery',
    driverId: 'driver-3',
    driverName: 'Tariq Hassan',
    pickupAddress: '250 Shawville Blvd SE, Calgary, AB T2Y 3Z1',
    pickupArea: 'Shawnessy',
    dropoffAddress: '2525 36 St NE, Calgary, AB T1Y 5T4',
    dropoffArea: 'Franklin',
    recipientPhone: '(403) 555-1005',
    manifest: [createManifestItem('big_package', 5, 'Bulk order')],
    isUrgent: false,
    isOutOfTown: false,
    status: 'picked_up',
    postedAt: hoursAgo(1),
    claimedAt: minsAgo(50),
    pickedUpAt: minsAgo(30),
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [
      { itemId: 'item-1', confirmedQty: 5, photoUrl: null, outOfTown: false },
    ],
    statusHistory: [
      createStatusEvent('posted', hoursAgo(1)),
      createStatusEvent('claimed', minsAgo(50)),
      createStatusEvent('en_route_pickup', minsAgo(45)),
      createStatusEvent('picked_up', minsAgo(30), '5 packages confirmed'),
    ],
    trackingCode: 'LVC-005-TH',
    tripId: null,
    retryCount: 0,
  },
  // En route to dropoff - Jenna (second delivery)
  {
    id: 'del-006',
    businessId: 'business-3',
    locationId: 'location-4',
    businessName: 'HomeGoods Plus',
    driverId: 'driver-2',
    driverName: 'Jenna Cole',
    pickupAddress: '3009 14 St SW, Calgary, AB T2T 3V6',
    pickupArea: 'Beltline',
    dropoffAddress: '8180 11 St SE, Calgary, AB T2H 2S9',
    dropoffArea: 'Shepard',
    recipientPhone: null,
    manifest: [
      createManifestItem('big_package', 2),
      createManifestItem('out_of_town'),
    ],
    isUrgent: false,
    isOutOfTown: true,
    status: 'en_route_dropoff',
    postedAt: hoursAgo(2),
    claimedAt: hoursAgo(1.5),
    pickedUpAt: minsAgo(40),
    deliveredAt: null,
    duration: null,
    proofPhotoUrl: null,
    recipientNote: null,
    calculatedRate: null,
    flags: [],
    verifications: [
      { itemId: 'item-2', confirmedQty: 2, photoUrl: null, outOfTown: true },
    ],
    statusHistory: [
      createStatusEvent('posted', hoursAgo(2)),
      createStatusEvent('claimed', hoursAgo(1.5)),
      createStatusEvent('en_route_pickup', hoursAgo(1.25)),
      createStatusEvent('picked_up', minsAgo(40)),
      createStatusEvent('en_route_dropoff', minsAgo(35)),
    ],
    trackingCode: 'LVC-006-JC',
    tripId: null,
    retryCount: 0,
  },
  // Delivered - completed 2 hours ago
  {
    id: 'del-007',
    businessId: 'business-1',
    locationId: 'location-1',
    businessName: 'FreshMart Grocery',
    driverId: 'driver-1',
    driverName: 'Marcus Reid',
    pickupAddress: '250 Shawville Blvd SE, Calgary, AB T2Y 3Z1',
    pickupArea: 'Shawnessy',
    dropoffAddress: '4820 Northland Dr NW, Calgary, AB T2L 2L4',
    dropoffArea: 'Dalhousie',
    recipientPhone: '(403) 555-1007',
    manifest: [createManifestItem('small_package', 1)],
    isUrgent: false,
    isOutOfTown: false,
    status: 'delivered',
    postedAt: hoursAgo(4),
    claimedAt: hoursAgo(3.5),
    pickedUpAt: hoursAgo(3),
    deliveredAt: hoursAgo(2),
    duration: '58 min',
    proofPhotoUrl: '/proof/del-007.jpg',
    recipientNote: 'Left at front desk',
    calculatedRate: 9.45,
    flags: [],
    verifications: [],
    statusHistory: [
      createStatusEvent('posted', hoursAgo(4)),
      createStatusEvent('claimed', hoursAgo(3.5)),
      createStatusEvent('en_route_pickup', hoursAgo(3.25)),
      createStatusEvent('picked_up', hoursAgo(3)),
      createStatusEvent('en_route_dropoff', hoursAgo(2.5)),
      createStatusEvent('delivered', hoursAgo(2), 'Left at front desk'),
    ],
    trackingCode: 'LVC-007-MR',
    tripId: null,
    retryCount: 0,
  },
  // Delivered - completed 4 hours ago
  {
    id: 'del-008',
    businessId: 'business-2',
    locationId: 'location-3',
    businessName: 'MedSupply Co',
    driverId: 'driver-2',
    driverName: 'Jenna Cole',
    pickupAddress: '1111 Centre St N, Calgary, AB T2E 2R2',
    pickupArea: 'Crescent Heights',
    dropoffAddress: '130 Crowfoot Crescent NW, Calgary, AB T3G 3P5',
    dropoffArea: 'Crowfoot',
    recipientPhone: '(403) 555-1008',
    manifest: [
      createManifestItem('big_package', 3),
      createManifestItem('rush'),
    ],
    isUrgent: true,
    isOutOfTown: false,
    status: 'delivered',
    postedAt: hoursAgo(6),
    claimedAt: hoursAgo(5.5),
    pickedUpAt: hoursAgo(5),
    deliveredAt: hoursAgo(4),
    duration: '42 min',
    proofPhotoUrl: '/proof/del-008.jpg',
    recipientNote: 'Handed to Sarah',
    calculatedRate: 38.85,
    flags: [],
    verifications: [],
    statusHistory: [
      createStatusEvent('posted', hoursAgo(6)),
      createStatusEvent('claimed', hoursAgo(5.5)),
      createStatusEvent('en_route_pickup', hoursAgo(5.25)),
      createStatusEvent('picked_up', hoursAgo(5)),
      createStatusEvent('en_route_dropoff', hoursAgo(4.5)),
      createStatusEvent('delivered', hoursAgo(4), 'Handed to Sarah'),
    ],
    trackingCode: 'LVC-008-JC',
    tripId: null,
    retryCount: 0,
  },
]

// System Settings
export const initialSettings: SystemSettings = {
  globalMaxJobs: 3,
  rushSlaMins: 45,
  intownTimeoutMins: 120,
  outOfTownTimeoutMins: 240,
  autoGenerateInvoices: true,
  invoiceDueDays: 15,
  autoSendInvoices: false,
  reminderDay1: 7,
  overdueDay: 7,
  escalationDay: 14,
  cancellationBeforeDepart: 0,
  cancellationEnRoute: 5,
}
